### ISSUE TITLE
DeepNote crashes when deleting a code cell

### ISSUE THREAD

**Issue by li-xin-yi** [Exafunction/codeium-chrome#16]
<img width="993" alt="image" src="https://github.com/Exafunction/codeium-chrome/assets/10118462/1842cd3a-9183-40e9-bb4e-56d909651666">

<img width="1209" alt="image" src="https://github.com/Exafunction/codeium-chrome/assets/10118462/2075f219-faeb-4dd8-9ea4-33f58b58f264">

**Comment by pqn** [comment]
What's the sequence of steps to reproduce?

**Comment by pqn** [comment]
I haven't had time to test, but I suspect we might need something like this at the top of `createInlineCompletionItem()`:
```ts
  if (editor?.getModel()?.isDisposed) {
    return undefined;
  }
```

**Comment by li-xin-yi** [comment]
@pqn 
Thanks for your suggestions. However, it doesn't work. I guess it is not actually relevant to `createInlineCompletionItem` or other components in Codeium extension. After looking into the JS files provided in the console, I strongly suspect it is because DeepNote invokes some dispose functions after deleting a cell, which includes some obvious React code (as there is almost no React dependency in Codeium extension itself). Maybe some code injected by Codeium make the Monaco dispose once and Deepnote forces it to dispose again. Just my guess, I'm not very familiar with the front-end tech or Codeium.

**Comment by pqn** [comment]
I'm not able to reproduce this unfortunately. Does it happen reliably for you?
