### ISSUE TITLE
Support for Dune Analytics IDE

### ISSUE THREAD

**Issue by rube-de** [Exafunction/codeium-chrome#17]
It would be great if the extension would support the Dune Analytics IDE www.dune.com

In Dune you can write SQL statements to aggregate data from the blockchain with DuneSQL, a variation of Trino.
https://dune.com/blog/introducing-dune-sql
https://dune.com/docs/query/

**Comment by pqn** [comment]
Even without specific code for DuneSQL we might be able to work reasonably if the dialect is similar to other SQL-family languages. It looks like they're using the Ace editor, which we don't currently have an integration for.

**Comment by pqn** [comment]
Consolidating this into #9.
