### ISSUE TITLE
Not Working on Jupyter Lab 4.0.2

### ISSUE THREAD

**Issue by lucianosb** [Exafunction/codeium-chrome#20]
I just started a new environment with the latest Jupyter Lab and noticed codeium wasn't working. When I checked the extension I got the message:

> "Only JupyterLab 3.x is supported"

I haven't checked yet if there is any breaking changes in 4.x that would require adjustments on the extension. However I felt the need to report and follow progress for now.

**Comment by pqn** [comment]
JupyterLab 4.x uses CodeMirror 6, which we are unable to inject code in right now. Any updates will probably posted in #9. Feel free to close this issue if that satisfies your concerns.

**Comment by lucianosb** [comment]
Thank you! I'll be following the other issue and see if I can contribute further.
