### ISSUE TITLE
Support for VSCode.dev?

### ISSUE THREAD

**Issue by cnaples79** [Exafunction/codeium-chrome#34]
Hello. Is there any way to get support for VSCode.dev and Insiders.vscode.dev? I've checked the compatibility list, and they are not on there, so I am not sure why they are or aren't compatible.

Unfortunately, the Codeium VSCode official extension does not work on the web versions of VS Code. So it would be nice to be able to use the Chrome extension at least.

Also, out of curiosity, is there any way to get an update on the sites that are on the compatibility list? CodeSandbox in particular, I am wondering if those sites will eventually get support or not.

This extension is great, please keep up the good work.

**Comment by pqn** [comment]
Glad you like the extension.

I gave a tiny update on the websites here: https://github.com/Exafunction/codeium-chrome/issues/9#issuecomment-1737852587

I don't think the Chrome extension can be easily made to work with the web version of VS Code. Support will require some VS Code extension changes and likely limiting the features available in the extension. Right now, I think it's a significant amount of work relative to the demand, so we aren't working on that right now. One way to use the extension in a VS Code environment in the browser is with Gitpod I believe.
