### ISSUE TITLE
Support godbolt's Compiler Explorer

### ISSUE THREAD

**Issue by glcraft** [Exafunction/codeium-chrome#4]
Add support to autocompletion for [godbolt's Compiler Explorer](https://godbolt.org/)

**Comment by glcraft** [comment]
I'll check out if I can implement this later (NB: I did not watch the extension code yet 😅 )

**Comment by pqn** [comment]
I took a quick look at this. The website does use Monaco, which we support, but trivially adding it to the list of sites in `script.ts` doesn't seem to work. I suspect some changes may be needed on https://github.com/compiler-explorer/compiler-explorer.

In particular, I haven't looked into it too closely, but we would need this feature to be enabled in the Monaco Webpack configuration: `{label: 'inlineCompletions', entry: 'vs/editor/contrib/inlineCompletions/browser/ghostText.contribution'}`

**Comment by glcraft** [comment]
It works fine now with PR https://github.com/Exafunction/codeium-chrome/pull/5. I close the issue 👍
