### ISSUE TITLE
Direct integration with no extension

### ISSUE THREAD

**Issue by hatemhosny** [Exafunction/codeium-chrome#41]
This is such a great product. Thank you!

I would be interested to implement in [LiveCodes](https://livecodes.io/) direct integration without the need to install the extension like the recently announced integration with CodeSandbox. https://github.com/Exafunction/codeium-chrome/issues/9#issuecomment-1823434399

Can you please guide?

Thank you

**Comment by pqn** [comment]
For first party integrations you can email your request to hello@codeium.com, and we can consider it on a case by case basis.
