### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [Exafunction/codeium-chrome#52]
Hello, 
Github Security Lab has found a vulnerability in codeium-chrome. Please enable [private-vulnerability-reporting ](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or provide a point of contact so that we can help you fix this issue.

**Comment by fortenforge** [comment]
Enabled private vulnerability reporting for all Exafunction repositories.

**Comment by Kwstubbs** [comment]
Thank you.
