### ISSUE TITLE
I add leetcode.cn to allow_list, but  work wrong with "Uncaught TypeError: e.languages.registerInlineCompletionsProvider is not a function"

### ISSUE THREAD

**Issue by beiyouwuyanzu** [Exafunction/codeium-chrome#8]
I use `npm run build` local to generate chrome extension and install it. but it wrong with blew` below image when I add "leetcode.cn" to allow_list and visit it.
I am not good at js, shoud I implement this function somewhere
![image](https://user-images.githubusercontent.com/30210999/236655805-3a08fb42-21e4-44d0-a588-c2a95bdf912f.png)

**Comment by pqn** [comment]
We've previously looked at compatibility for LeetCode, and it's incompatible with Codeium. I've added a bit more detail about that here: https://github.com/Exafunction/codeium-chrome/issues/9
